import { useEffect, useMemo, useState } from "react";
import { useOutletContext } from "react-router-dom";
import { BellRing } from "lucide-react";
import PageHeader from "../components/PageHeader.jsx";
import SectionHeader from "../components/SectionHeader.jsx";
import AlertCard from "../components/AlertCard.jsx";
import { alerts as seedAlerts, alertSeverityCounts } from "../data/alerts.js";

const TABS = ["All", "Critical", "High", "Medium", "Low"];

export default function Alerts() {
  const { openProject } = useOutletContext();
  const [tab, setTab] = useState("All");
  const [reviewedIds, setReviewedIds] = useState(() =>
    new Set(seedAlerts.filter((a) => a.reviewed).map((a) => a.id))
  );

  useEffect(() => {
    document.title = "Alerts · LADI Portal";
  }, []);

  const toggleReviewed = (id) =>
    setReviewedIds((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });

  const filtered = useMemo(
    () => (tab === "All" ? seedAlerts : seedAlerts.filter((a) => a.severity === tab)),
    [tab]
  );

  const unreviewedCount = seedAlerts.length - reviewedIds.size;

  return (
    <>
      <PageHeader
        title="Early-Warning Alert Center"
        subtitle="Review, triage and act on alerts generated by threshold rules and risk movements."
      >
        <span className="module-tag">Phase 2 Module</span>
      </PageHeader>

      <div className="stat-strip">
        <article className="card stat-tile">
          <span className="stat-tile-label">Total Alerts</span>
          <span className="stat-tile-value">{seedAlerts.length}</span>
          <span className="stat-tile-hint">{unreviewedCount} awaiting review</span>
        </article>
        <article className="card stat-tile">
          <span className="stat-tile-label">Critical</span>
          <span className="stat-tile-value">{alertSeverityCounts.Critical || 0}</span>
          <span className="stat-tile-hint">Immediate action required</span>
        </article>
        <article className="card stat-tile">
          <span className="stat-tile-label">High</span>
          <span className="stat-tile-value">{alertSeverityCounts.High || 0}</span>
          <span className="stat-tile-hint">Escalation review advised</span>
        </article>
        <article className="card stat-tile">
          <span className="stat-tile-label">Medium</span>
          <span className="stat-tile-value">{alertSeverityCounts.Medium || 0}</span>
          <span className="stat-tile-hint">Watch indicators active</span>
        </article>
        <article className="card stat-tile">
          <span className="stat-tile-label">Information</span>
          <span className="stat-tile-value">{alertSeverityCounts.Low || 0}</span>
          <span className="stat-tile-hint">Routine system events</span>
        </article>
      </div>

      <SectionHeader
        title={`Alert Queue · ${filtered.length} shown`}
        subtitle="Filter by severity; mark items reviewed as they are actioned"
      />

      <div className="chip-row" role="tablist" aria-label="Filter alerts by severity">
        {TABS.map((t) => {
          const count =
            t === "All" ? seedAlerts.length : alertSeverityCounts[t] || 0;
          return (
            <button
              key={t}
              role="tab"
              aria-selected={tab === t}
              className={`chip${tab === t ? " active" : ""}`}
              onClick={() => setTab(t)}
            >
              {t === "Low" ? "Information" : t}
              <span className="chip-count">{count}</span>
            </button>
          );
        })}
      </div>

      {filtered.length > 0 ? (
        <div className="alert-list">
          {filtered.map((alert) => (
            <AlertCard
              key={alert.id}
              alert={alert}
              reviewed={reviewedIds.has(alert.id)}
              onToggleReviewed={toggleReviewed}
              onOpenProject={openProject}
            />
          ))}
        </div>
      ) : (
        <div className="card placeholder-panel">
          <span className="placeholder-icon" aria-hidden="true">
            <BellRing size={24} />
          </span>
          <h3>No {tab.toLowerCase()}-severity alerts</h3>
          <p>There is nothing in this severity bucket right now.</p>
        </div>
      )}
    </>
  );
}
